"""Nested spatial controls for privileged street-view KD on Haidian.

All paired regions enter one nested spatial cross-validation. Within every
outer-training fold, teacher signals are generated by grouped cross-fitting and
KD strength is selected on a spatially disjoint validation subset. Outer-test
inference for every deployable student uses satellite features only.

Two correspondence controls are included:

* global shuffled: street features are deranged within each data partition;
* local shuffled: street features are deranged only among samples belonging to
  the same spatial block and partition.

Model, spatial-split and shuffle randomness have independent command-line
seeds.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import StandardScaler
from tqdm.auto import tqdm

from release_utils import parse_number_list
from run_nested_spatial_kd import (
    deranged_modality_copy,
    predict_student,
    predict_teacher,
    resolve_device,
    select_kd_student_by_spatial_validation,
    select_kd_student_with_isolated_validation,
    spatial_groups,
    spatial_train_validation_split,
    tensor,
    train_supervised_student,
    train_teacher,
)


STUDENT_KINDS = ("paired", "global_shuffled", "local_shuffled", "satellite")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--features", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--targets",
        default="population",
        help="Comma-separated target names stored in the feature archive.",
    )
    parser.add_argument("--outer-folds", type=int, default=5)
    parser.add_argument("--inner-folds", type=int, default=4)
    parser.add_argument("--spatial-blocks", type=int, default=25)
    parser.add_argument("--validation-fraction", type=float, default=0.15)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--epochs", type=int, default=250)
    parser.add_argument("--patience", type=int, default=25)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--lambda-pred", type=float, default=0.5)
    parser.add_argument(
        "--kd-weight-grid",
        default="0,0.25,0.5,1,2,4,8,16,32,64",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--spatial-seed", type=int, default=42)
    parser.add_argument(
        "--shuffle-seed",
        type=int,
        default=42,
        help="Shuffling seed, independent of model and spatial-split seeds.",
    )
    parser.add_argument("--device", default="auto")
    parser.add_argument("--no-progress", action="store_true")
    parser.add_argument(
        "--strict-label-isolation",
        action="store_true",
        help=(
            "Keep the KD-weight selection-validation labels out of teacher "
            "cross-fitting and candidate-model early stopping. Without this "
            "flag the less-isolated selection protocol is used."
        ),
    )
    return parser.parse_args()


def load_archive(path: Path) -> dict[str, np.ndarray]:
    archive = np.load(path, allow_pickle=False)
    required = {
        "sample_id",
        "latitude",
        "longitude",
        "satellite_features",
        "street_features",
        "targets",
        "target_names",
    }
    missing = sorted(required.difference(archive.files))
    if missing:
        raise ValueError(f"{path} is missing arrays: {missing}")
    result = {name: archive[name] for name in required}
    n = len(result["sample_id"])
    for name in required.difference({"target_names"}):
        if len(result[name]) != n:
            raise ValueError(f"Inconsistent sample count for {name} in {path}")
    for name in ("latitude", "longitude", "satellite_features", "street_features", "targets"):
        if not np.isfinite(result[name]).all():
            raise ValueError(f"Non-finite values in {name} of {path}")
    sample_ids = result["sample_id"].astype(str)
    if len(np.unique(sample_ids)) != len(sample_ids):
        raise ValueError(f"Duplicate sample IDs in {path}")
    result["sample_id"] = sample_ids
    return result


def local_deranged_modality_copy(
    modality: np.ndarray,
    partitions: list[np.ndarray],
    spatial_group: np.ndarray,
    seed: int,
) -> tuple[np.ndarray, dict[str, int]]:
    """Derange rows within every partition-by-spatial-block cell.

    A spatial block with one sample cannot be deranged. Such a sample is
    deranged against another singleton (or, if necessary, inside its whole
    partition) and is counted in diagnostics. With the default 25 blocks this
    fallback should normally be unused.
    """
    shuffled = modality.copy()
    rng = np.random.default_rng(seed)
    singleton_count = 0
    fallback_count = 0
    cell_count = 0
    for partition in partitions:
        partition = np.asarray(partition, dtype=np.int64)
        if len(partition) < 2:
            raise ValueError("Every shuffled partition must contain at least two samples.")
        singletons: list[int] = []
        for group in np.unique(spatial_group[partition]):
            cell = partition[spatial_group[partition] == group]
            cell_count += 1
            if len(cell) < 2:
                singletons.extend(cell.tolist())
                continue
            order = rng.permutation(cell)
            shuffled[order] = modality[np.roll(order, 1)]
        singleton_count += len(singletons)
        if singletons:
            singleton_array = np.asarray(singletons, dtype=np.int64)
            if len(singleton_array) >= 2:
                order = rng.permutation(singleton_array)
                shuffled[order] = modality[np.roll(order, 1)]
            else:
                index = int(singleton_array[0])
                candidates = partition[partition != index]
                source = int(rng.choice(candidates))
                shuffled[index] = modality[source]
            fallback_count += len(singletons)
    return shuffled, {
        "local_cells": cell_count,
        "local_singletons": singleton_count,
        "local_fallback_samples": fallback_count,
    }


def prediction_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
    return {
        "R2": float(r2_score(y_true, y_pred)),
        "RMSE": float(np.sqrt(mean_squared_error(y_true, y_pred))),
        "MAE": float(mean_absolute_error(y_true, y_pred)),
    }


def summarize(predictions: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for target_name, target_frame in predictions.groupby("target", sort=False):
        scores = {
            model: prediction_metrics(frame["y_true"].to_numpy(), frame["y_pred"].to_numpy())
            for model, frame in target_frame.groupby("model")
        }
        sat = scores["sat_supervised"]
        no_privilege = scores["prediction_kd_no_privilege"]
        full_gain = scores["sat_real_sv_teacher"]["R2"] - sat["R2"]
        global_gain = (
            scores["sat_real_sv_teacher"]["R2"]
            - scores["sat_global_shuffled_real_sv"]["R2"]
        )
        local_gain = (
            scores["sat_real_sv_teacher"]["R2"]
            - scores["sat_local_shuffled_real_sv"]["R2"]
        )
        for model, score in scores.items():
            is_student = model.startswith("prediction_kd_")
            row = {
                "target": target_name,
                "model": model,
                "N": int((target_frame["model"] == model).sum()),
                **score,
                "Delta_R2_vs_Sat": score["R2"] - sat["R2"],
                "Delta_R2_vs_no_privilege": (
                    score["R2"] - no_privilege["R2"] if is_student else np.nan
                ),
                "Full_oracle_gain_R2": full_gain,
                "Global_correspondence_oracle_gain_R2": global_gain,
                "Local_correspondence_oracle_gain_R2": local_gain,
                "Full_DRR": (
                    (score["R2"] - no_privilege["R2"]) / full_gain
                    if is_student and full_gain > 0
                    else np.nan
                ),
            }
            if model == "prediction_kd_paired":
                row.update(
                    {
                        "Delta_R2_vs_global_shuffled_KD": (
                            score["R2"] - scores["prediction_kd_global_shuffled"]["R2"]
                        ),
                        "Delta_R2_vs_local_shuffled_KD": (
                            score["R2"] - scores["prediction_kd_local_shuffled"]["R2"]
                        ),
                        "Delta_R2_vs_satellite_teacher_KD": (
                            score["R2"] - scores["prediction_kd_satellite_teacher"]["R2"]
                        ),
                        "Global_correspondence_recovery_ratio": (
                            (score["R2"] - scores["prediction_kd_global_shuffled"]["R2"])
                            / global_gain
                            if global_gain > 0
                            else np.nan
                        ),
                        "Local_correspondence_recovery_ratio": (
                            (score["R2"] - scores["prediction_kd_local_shuffled"]["R2"])
                            / local_gain
                            if local_gain > 0
                            else np.nan
                        ),
                    }
                )
            rows.append(row)
    return pd.DataFrame(rows)


def add_prediction_rows(
    rows: list[dict[str, object]],
    data: dict[str, np.ndarray],
    target_name: str,
    target: np.ndarray,
    outer_test: np.ndarray,
    outer_fold: int,
    spatial_group: np.ndarray,
    model: str,
    prediction: np.ndarray,
    kd_weight: float,
) -> None:
    for position, index in enumerate(outer_test):
        rows.append(
            {
                "target": target_name,
                "sample_id": data["sample_id"][index],
                "latitude": data["latitude"][index],
                "longitude": data["longitude"][index],
                "spatial_group": spatial_group[index],
                "outer_fold": outer_fold,
                "model": model,
                "y_true": target[index],
                "y_pred": prediction[position],
                "kd_weight": kd_weight,
            }
        )


def main() -> None:
    args = parse_args()
    device = resolve_device(args.device)
    kd_weights = parse_number_list(args.kd_weight_grid, float)
    if 0.0 not in kd_weights or any(weight < 0 for weight in kd_weights):
        raise ValueError("--kd-weight-grid must include zero and contain no negatives.")
    if args.outer_folds < 2 or args.inner_folds < 2:
        raise ValueError("Both outer and inner folds must be at least two.")
    if args.spatial_blocks < args.outer_folds:
        raise ValueError("--spatial-blocks must be at least --outer-folds.")

    data = load_archive(args.features)
    n_samples = len(data["sample_id"])
    spatial_group = spatial_groups(
        data["latitude"], data["longitude"], args.spatial_blocks, args.spatial_seed
    )
    unique_groups = np.unique(spatial_group)
    if len(unique_groups) < args.outer_folds:
        raise ValueError("Too few spatial groups for the requested outer folds.")
    fold_assignment = np.full(n_samples, -1, dtype=np.int64)
    outer_splitter = GroupKFold(n_splits=args.outer_folds)
    all_indices = np.arange(n_samples)
    for outer_fold, (_, test_position) in enumerate(
        outer_splitter.split(all_indices, groups=spatial_group), start=1
    ):
        fold_assignment[test_position] = outer_fold

    requested = [item.strip() for item in args.targets.split(",") if item.strip()]
    target_names = data["target_names"].tolist()
    missing_targets = [name for name in requested if name not in target_names]
    if missing_targets:
        raise ValueError(f"Targets not present in archives: {missing_targets}")

    prediction_rows: list[dict[str, object]] = []
    selection_rows: list[dict[str, object]] = []
    signal_rows: list[dict[str, object]] = []
    shuffle_rows: list[dict[str, object]] = []
    isolation_rows: list[dict[str, object]] = []
    total_steps = len(requested) * args.outer_folds
    progress = tqdm(total=total_steps, desc="Haidian nested spatial controls", disable=args.no_progress)

    for target_position, target_name in enumerate(requested):
        target = data["targets"][:, target_names.index(target_name)].astype(np.float64)
        for outer_fold in range(1, args.outer_folds + 1):
            progress.set_postfix(target=target_name, fold=outer_fold)
            outer_test = np.flatnonzero(fold_assignment == outer_fold)
            outer_train = np.flatnonzero(fold_assignment != outer_fold)
            model_seed = args.seed + 10000 * target_position + 1000 * outer_fold
            split_seed = args.spatial_seed + 10000 * target_position + 1000 * outer_fold
            shuffle_seed = args.shuffle_seed + 10000 * target_position + 1000 * outer_fold

            sat_scaler = StandardScaler().fit(data["satellite_features"][outer_train])
            street_scaler = StandardScaler().fit(data["street_features"][outer_train])
            satellite_scaled = sat_scaler.transform(data["satellite_features"]).astype(np.float32)
            street_scaled = street_scaler.transform(data["street_features"]).astype(np.float32)
            satellite = tensor(satellite_scaled, device)
            street = tensor(street_scaled, device)

            final_train, final_validation = spatial_train_validation_split(
                outer_train,
                spatial_group,
                args.validation_fraction,
                split_seed + 99,
            )
            crossfit_pool = final_train if args.strict_label_isolation else outer_train

            soft = {
                kind: np.full(n_samples, np.nan, dtype=np.float64)
                for kind in STUDENT_KINDS
            }
            inner_groups = spatial_group[crossfit_pool]
            inner_fold_count = min(args.inner_folds, len(np.unique(inner_groups)))
            inner_splitter = GroupKFold(n_splits=inner_fold_count)
            inner_progress = tqdm(
                enumerate(
                    inner_splitter.split(
                        crossfit_pool, target[crossfit_pool], inner_groups
                    ),
                    start=1,
                ),
                total=inner_fold_count,
                desc=f"cross-fit target={target_name} outer={outer_fold}",
                leave=False,
                disable=args.no_progress,
            )
            for inner_fold, (fit_position, hold_position) in inner_progress:
                inner_pool = crossfit_pool[fit_position]
                inner_hold = crossfit_pool[hold_position]
                inner_train, inner_validation = spatial_train_validation_split(
                    inner_pool,
                    spatial_group,
                    args.validation_fraction,
                    split_seed + inner_fold,
                )
                teacher_seed = model_seed + 10 * inner_fold

                paired_teacher = train_teacher(
                    satellite,
                    street,
                    target,
                    inner_train,
                    inner_validation,
                    args,
                    device,
                    teacher_seed,
                )
                soft["paired"][inner_hold] = predict_teacher(
                    paired_teacher, satellite, street, inner_hold
                )[0]

                global_array = deranged_modality_copy(
                    street_scaled,
                    [inner_train, inner_validation, inner_hold],
                    shuffle_seed + inner_fold,
                )
                global_street = tensor(global_array, device)
                global_teacher = train_teacher(
                    satellite,
                    global_street,
                    target,
                    inner_train,
                    inner_validation,
                    args,
                    device,
                    teacher_seed,
                )
                soft["global_shuffled"][inner_hold] = predict_teacher(
                    global_teacher, satellite, global_street, inner_hold
                )[0]

                local_array, local_diagnostics = local_deranged_modality_copy(
                    street_scaled,
                    [inner_train, inner_validation, inner_hold],
                    spatial_group,
                    shuffle_seed + 500000 + inner_fold,
                )
                local_street = tensor(local_array, device)
                local_teacher = train_teacher(
                    satellite,
                    local_street,
                    target,
                    inner_train,
                    inner_validation,
                    args,
                    device,
                    teacher_seed,
                )
                soft["local_shuffled"][inner_hold] = predict_teacher(
                    local_teacher, satellite, local_street, inner_hold
                )[0]
                shuffle_rows.append(
                    {
                        "target": target_name,
                        "outer_fold": outer_fold,
                        "stage": "cross_fit",
                        "inner_fold": inner_fold,
                        **local_diagnostics,
                    }
                )

                satellite_teacher = train_supervised_student(
                    satellite,
                    target,
                    inner_train,
                    inner_validation,
                    args,
                    device,
                    teacher_seed,
                )
                soft["satellite"][inner_hold] = predict_student(
                    satellite_teacher, satellite, inner_hold
                )[0]

            for kind, values in soft.items():
                if not np.isfinite(values[crossfit_pool]).all():
                    raise RuntimeError(
                        f"Incomplete {kind} cross-fitted targets for {target_name}, "
                        f"outer fold {outer_fold}."
                    )
                signal_rows.append(
                    {
                        "target": target_name,
                        "outer_fold": outer_fold,
                        "teacher_kind": kind,
                        "OOF_R2_outer_train": float(
                            r2_score(target[crossfit_pool], values[crossfit_pool])
                        ),
                        "OOF_MAE_outer_train": float(
                            mean_absolute_error(
                                target[crossfit_pool], values[crossfit_pool]
                            )
                        ),
                    }
                )

            dummy_embedding = np.zeros((n_samples, args.hidden_dim), dtype=np.float32)
            students: dict[str, object] = {}
            selected_weights: dict[str, float] = {}
            for kind in STUDENT_KINDS:
                if args.strict_label_isolation:
                    (
                        student,
                        selected_weight,
                        validation_r2,
                        candidate_train,
                        candidate_earlystop,
                    ) = select_kd_student_with_isolated_validation(
                        satellite=satellite,
                        target=target,
                        teacher_prediction=soft[kind],
                        teacher_embedding=dummy_embedding,
                        selection_train_indices=final_train,
                        selection_validation_indices=final_validation,
                        groups=spatial_group,
                        candidate_weights=kd_weights,
                        relation_weight=0.0,
                        validation_fraction=args.validation_fraction,
                        split_seed=split_seed + 700,
                        args=args,
                        device=device,
                        seed=model_seed + 100,
                    )
                else:
                    student, selected_weight, validation_r2 = (
                        select_kd_student_by_spatial_validation(
                            satellite=satellite,
                            target=target,
                            teacher_prediction=soft[kind],
                            teacher_embedding=dummy_embedding,
                            train_indices=final_train,
                            validation_indices=final_validation,
                            candidate_weights=kd_weights,
                            relation_weight=0.0,
                            args=args,
                            device=device,
                            seed=model_seed + 100,
                        )
                    )
                    candidate_train = final_train
                    candidate_earlystop = final_validation
                students[kind] = student
                selected_weights[kind] = selected_weight
                selection_rows.append(
                    {
                        "target": target_name,
                        "outer_fold": outer_fold,
                        "teacher_kind": kind,
                        "selected_weight": selected_weight,
                        "selected_validation_R2": validation_r2,
                        "strict_label_isolation": args.strict_label_isolation,
                    }
                )

            if args.strict_label_isolation:
                isolation_rows.append(
                    {
                        "target": target_name,
                        "outer_fold": outer_fold,
                        "N_outer_train": len(outer_train),
                        "N_selection_train": len(final_train),
                        "N_selection_validation": len(final_validation),
                        "N_candidate_train": len(candidate_train),
                        "N_candidate_earlystop": len(candidate_earlystop),
                        "selection_validation_in_teacher_crossfit_pool": len(
                            set(final_validation.tolist()).intersection(
                                crossfit_pool.tolist()
                            )
                        ),
                        "selection_validation_in_candidate_fit_or_earlystop": len(
                            set(final_validation.tolist()).intersection(
                                np.concatenate(
                                    [candidate_train, candidate_earlystop]
                                ).tolist()
                            )
                        ),
                        "outer_test_in_any_internal_set": len(
                            set(outer_test.tolist()).intersection(
                                np.concatenate(
                                    [crossfit_pool, final_validation]
                                ).tolist()
                            )
                        ),
                    }
                )

            if args.strict_label_isolation:
                no_privilege = select_kd_student_with_isolated_validation(
                    satellite=satellite,
                    target=target,
                    teacher_prediction=soft["paired"],
                    teacher_embedding=dummy_embedding,
                    selection_train_indices=final_train,
                    selection_validation_indices=final_validation,
                    groups=spatial_group,
                    candidate_weights=[0.0],
                    relation_weight=0.0,
                    validation_fraction=args.validation_fraction,
                    split_seed=split_seed + 700,
                    args=args,
                    device=device,
                    seed=model_seed + 100,
                )[0]
            else:
                no_privilege = select_kd_student_by_spatial_validation(
                    satellite=satellite,
                    target=target,
                    teacher_prediction=soft["paired"],
                    teacher_embedding=dummy_embedding,
                    train_indices=final_train,
                    validation_indices=final_validation,
                    candidate_weights=[0.0],
                    relation_weight=0.0,
                    args=args,
                    device=device,
                    seed=model_seed + 100,
                )[0]
            baseline = train_supervised_student(
                satellite,
                target,
                final_train,
                final_validation,
                args,
                device,
                model_seed + 100,
            )
            paired_oracle = train_teacher(
                satellite,
                street,
                target,
                final_train,
                final_validation,
                args,
                device,
                model_seed + 101,
            )
            parameter_matched = train_teacher(
                satellite,
                satellite,
                target,
                final_train,
                final_validation,
                args,
                device,
                model_seed + 101,
            )

            global_final_array = deranged_modality_copy(
                street_scaled,
                [final_train, final_validation, outer_test],
                shuffle_seed + 202,
            )
            global_final = tensor(global_final_array, device)
            global_oracle = train_teacher(
                satellite,
                global_final,
                target,
                final_train,
                final_validation,
                args,
                device,
                model_seed + 101,
            )
            local_final_array, local_diagnostics = local_deranged_modality_copy(
                street_scaled,
                [final_train, final_validation, outer_test],
                spatial_group,
                shuffle_seed + 500202,
            )
            shuffle_rows.append(
                {
                    "target": target_name,
                    "outer_fold": outer_fold,
                    "stage": "final",
                    "inner_fold": np.nan,
                    **local_diagnostics,
                }
            )
            local_final = tensor(local_final_array, device)
            local_oracle = train_teacher(
                satellite,
                local_final,
                target,
                final_train,
                final_validation,
                args,
                device,
                model_seed + 101,
            )

            predictions = {
                "sat_supervised": predict_student(baseline, satellite, outer_test)[0],
                "sat_parameter_matched": predict_teacher(
                    parameter_matched, satellite, satellite, outer_test
                )[0],
                "sat_real_sv_teacher": predict_teacher(
                    paired_oracle, satellite, street, outer_test
                )[0],
                "sat_global_shuffled_real_sv": predict_teacher(
                    global_oracle, satellite, global_final, outer_test
                )[0],
                "sat_local_shuffled_real_sv": predict_teacher(
                    local_oracle, satellite, local_final, outer_test
                )[0],
                "prediction_kd_no_privilege": predict_student(
                    no_privilege, satellite, outer_test
                )[0],
                "prediction_kd_paired": predict_student(
                    students["paired"], satellite, outer_test
                )[0],
                "prediction_kd_global_shuffled": predict_student(
                    students["global_shuffled"], satellite, outer_test
                )[0],
                "prediction_kd_local_shuffled": predict_student(
                    students["local_shuffled"], satellite, outer_test
                )[0],
                "prediction_kd_satellite_teacher": predict_student(
                    students["satellite"], satellite, outer_test
                )[0],
            }
            for model, prediction in predictions.items():
                if model == "prediction_kd_no_privilege":
                    weight = 0.0
                elif model.startswith("prediction_kd_"):
                    kind = model.removeprefix("prediction_kd_").replace("_teacher", "")
                    weight = selected_weights[kind]
                else:
                    weight = np.nan
                add_prediction_rows(
                    prediction_rows,
                    data,
                    target_name,
                    target,
                    outer_test,
                    outer_fold,
                    spatial_group,
                    model,
                    prediction,
                    weight,
                )
            progress.update(1)
    progress.close()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    predictions = pd.DataFrame(prediction_rows)
    pooled = summarize(predictions)
    predictions.to_csv(args.output_dir / "outer_oof_predictions.csv", index=False)
    pooled.to_csv(args.output_dir / "pooled_summary.csv", index=False)
    fold_summaries = []
    for fold, frame in predictions.groupby("outer_fold"):
        summary = summarize(frame)
        summary.insert(1, "outer_fold", fold)
        fold_summaries.append(summary)
    pd.concat(fold_summaries, ignore_index=True).to_csv(
        args.output_dir / "fold_metrics.csv", index=False
    )
    pd.DataFrame(selection_rows).to_csv(
        args.output_dir / "kd_weight_selection.csv", index=False
    )
    pd.DataFrame(signal_rows).to_csv(
        args.output_dir / "teacher_signal_diagnostics.csv", index=False
    )
    pd.DataFrame(shuffle_rows).to_csv(
        args.output_dir / "local_shuffle_diagnostics.csv", index=False
    )
    if args.strict_label_isolation:
        pd.DataFrame(isolation_rows).to_csv(
            args.output_dir / "label_isolation_audit.csv", index=False
        )
    pd.DataFrame(
        {
            "sample_id": data["sample_id"],
            "latitude": data["latitude"],
            "longitude": data["longitude"],
            "spatial_group": spatial_group,
            "outer_fold": fold_assignment,
        }
    ).to_csv(args.output_dir / "spatial_assignment.csv", index=False)

    config = vars(args).copy()
    for key in ("features", "output_dir"):
        config[key] = str(config[key])
    config.update(
        {
            "device_resolved": str(device),
            "N_pairs": n_samples,
            "controls": list(STUDENT_KINDS),
            "outer_test_used_for_selection": False,
            "selection_protocol": (
                "nested_label_isolated"
                if args.strict_label_isolation
                else "less_isolated"
            ),
        }
    )
    (args.output_dir / "run_config.json").write_text(
        json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print("Pooled Haidian nested spatial control summary")
    print(pooled.to_string(index=False))
    print("\nKD weight selection")
    print(pd.DataFrame(selection_rows).to_string(index=False))
    print("\nLocal shuffle diagnostics")
    print(pd.DataFrame(shuffle_rows).groupby("stage").sum(numeric_only=True).to_string())
    print(f"Saved results to: {args.output_dir}")


if __name__ == "__main__":
    main()
